baseURL = 'https://nash-efp.github.io/junki-asano.github.io/'
languageCode = 'ja'
title = 'junki asano'
theme = "paper"

disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

publishDir = "docs"
canonifyurls = true # https://qiita.com/ysdyt/items/a581277dd1312a0e83c3


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'nash_efp'               # twitter.com/YOUR_TWITTER_ID
  github = 'nash-efp'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'junki-asano/'             # linkedin.com/in/YOUR_LINKEDIN_ID
  podcast = 'https://shirokane-kougyou.github.io/' # podcast url
  note = 'https://note.com/nash_efp' # note url
  qiita = 'https://qiita.com/nash_efp' # qiita url
  # rss = true                               # show rss icon

  # home page profile
  avatar = 'https://pbs.twimg.com/profile_images/1267464591937646592/4P7G4aGc_400x400.jpg'                 # gravatar email or image url
  name = 'junki asano'
  bio = 'Data Scientist / BrainPad.Inc'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

  # giscus
[params.giscus]
  repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
  repoId = 'YOUR_GISCUS_REPO_ID'
  category = 'YOUR__GISCUS_CATEGORY'
  categoryId = 'YOUR_GISCUS_CATEGORY_ID'
  mapping = 'pathname'
  theme = 'light'
  lang = 'zh-CN'