baseURL = 'https://github.com/nash-efp/junki-asano.github.io'
languageCode = 'ja'
title = 'Home Page'
theme = "paper"

disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'nash_efp'               # twitter.com/YOUR_TWITTER_ID
  github = 'nash-efp'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'junki-asano/'             # linkedin.com/in/YOUR_LINKEDIN_ID
  podcast = 'https://shirokane-kougyou.github.io/' # podcast url
  note = "https://note.com/nash_efp" # note url
  # rss = true                               # show rss icon

  # home page profile
  avatar = 'https://github.com/nash-efp/junki-asano.github.io/main/data/images/asano_icon.png'                 # gravatar email or image url
  name = 'junki asano'
  bio = 'Data Scientist / BrainPad.Inc'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

  # giscus
[params.giscus]
  repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
  repoId = 'YOUR_GISCUS_REPO_ID'
  category = 'YOUR__GISCUS_CATEGORY'
  categoryId = 'YOUR_GISCUS_CATEGORY_ID'
  mapping = 'pathname'
  theme = 'light'
  lang = 'zh-CN'